### ISSUE TITLE
X-Rite i1Profiler package seam to have changed its structure

### ISSUE THREAD

**Issue by henningkessler** [autopkg/mosen-recipes#24]
Hello mosen,

running your i1Profiler.munki recipe gives me the following error:
```
The following recipes failed:
    i1Profiler.munki
        Error in local.munki.i1Profiler: Processor: FileCreator: Error: Can't create file at /Users/master707/Library/AutoPkg/Cache/local.munki.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall: [Errno 2] No such file or directory: u'/Users/master707/Library/AutoPkg/Cache/local.munki.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'
```

 I guess they changed the structure of the package as the former postinstall script is now named to postflight and has the following path:
```i1Profiler.pkg/i1profilerPostflight.pkg/Scripts/postflight```

Or am I totally wrong?

Regards

Henning

**Comment by mosen** [comment]
I'll check it out shortly

**Comment by mosen** [comment]
You're correct the structure has changed. I'll update the postflight

**Comment by henningkessler** [comment]
Great, thanks a lot

Henning .

**Comment by mosen** [comment]
I've committed a new version and im just testing. It should not fail at loginwindow but I still need to test this case.
